server_ip = "127.0.0.1"
login_port = 50050
auth_port = 50000
game_port = 50001

rsa_private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC5MrCdebqKG8WD
1dqG3lvAHi/7k05Qj9OXoThXi5+7qlJIfVbh5rS0W+5BnSClgJodoJu0qdqvI/FW
xN7CIPsNlJm62VO1Q1GXNBMrm4Ejwcw8J7rnj6OAx/tjo2+/OzTyBrc/Ue8ox9q7
24bzcUYegdwxANQiUO9EJgOZoeXfhRj2+19WxRzhUVcLJdSjc8pnXiASeHeeXE5m
5WQ8TtrVP7gx3OLE0KaF/VYc+gSIFSwPhNheAVfqr1gZR4Yx5ZMA5/hUn0+GVqtn
2Qyx4sQGao0gOAw22fJZ0zGnv+nYVkV+kEXGFPPGLj7R8BhimKCHWluDbMjx4PRK
Mdpz8XPFAgMBAAECggEAYosOXzy+fW55ksTgGpOGzptBfOPM8CEXvb8Tc8HfpMPk
NJ489McFsFKaXF93V5kuaEVllKQssLS3XiwzO6jA7WD8y+eIGxNO/t2+tZ1xAc3F
Ft0tHrnXjlba9RGqDF88tOvN5et7DoAJa5xMGo1TejgvKgP+3KOkLObtU3pKDryi
gSjiloxrNqv4VWYxWqP12bKQLjkE/0KPG5czDjl9Volc0OAnE18Zr7VxP/VgM/WN
9A/mv6wnWQogammIW+Wt8Uk9+G78OfthpErSJe4cD//lK/k2ChXbtsmcLHVrOsNz
x2HXo1ymuYToROSpxxPXGAGb6F3kYSVd+WAlaAJKAQKBgQDzLFNtFkfx/Hm98695
QKtBc7UxiMG4KMmQmshgltznhW30m6LC2FmQrdMVe1pta1ODUsxvxKTmsa7R9Vwt
b3qTijmQijPjQgnBctzeaMTwyfDF2cIuDdr7UDnUKgozjqulipCTlszP0aLqlbbQ
RNP8xErzioK7wUHUjmIuT69fcQKBgQDC94AKr/bIUugMqRAAWYYb2bLX3N2LTklm
mSYgj1RiMSwfmU2fhB30yeZ42qjPP11G8QFFTlfASudRi2K4+f10ZphyO2/LG22K
aDzLUlXHgRnV/OKAdoxmlq+aDg3d3qv8fUQfYe75cucM+9ILtyCQaW85Jpeeqzws
BGoFd6fXlQKBgQDazYKPgGHiChQc59x3FMpDjXJ3DJ+KLiEX3T35MyW3qKaEV1n/
Sh5lARMSnDiEhfLSEjljRCRAc5Zi0wxK0akQgmpDdSc1ECGpD8pO0SSLqJjd3Y9M
Uyk7wjcWgXFGbNRjkqd+NU06nV2jCG1DPvsj0BfExVfWyxCJykfrdcXN8QKBgASH
HvAgmgiY9E6m9normhO3gJHGzVZY4ReC4wHKklkdbzrkoorb1J5EuheAbH8zp4To
P/FOGneaxbh9FjPZimtTnqK4gqYi4u5d8Vt/dAKIGwN/NftpxWT0hut6/BN1AmWA
uz5HVfdxFbCVgJFJFXaFHFIldUv4ChOznoq19q3pAoGBAKKvskK3bWVO3uUO6jHb
J2IgmFVaYHFx6JRTHa7jsbUTmYk0xDmO8jN6HIt6O9zE05wDwunaGi5QneVtgJEA
G6y0FZAowR/8Y/qDqfwJfqDilPb7MqllOlucSJiQhIRdNixb1H1HzX6pH9hXktYk
0IHsEKcMr/P/gMCXxFfl1xAi
-----END PRIVATE KEY-----"""
