server_ip = "0.0.0.0"
login_port = 50050
auth_port = 0
game_port = 0

rsa_private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC5MrCdebqKG8WD
1dqG3lvAHi/7k05Qj9OXoThXi5+7qlJIfVbh5rS0W+5BnSClgJodoJu0qdqvI/FW
xN7CIPsNlJm62VO1Q1GXNBMrm4Ejwcw8J7rnj6OAx/tjo2+/OzTyBrc/Ue8ox9q7
24bzcUYegdwxANQiUO9EJgOZoeXfhRj2+19WxRzhUVcLJdSjc8pnXiASeHeeXE5m
5WQ8TtrVP7gx3OLE0KaF/VYc+gSIFSwPhNheAVfqr1gZR4Yx5ZMA5/hUn0+GVqtn
2Qyx4sQGao0gOAw22fJZ0zGnv+nYVkV+kEXGFPPGLj7R8BhimKCHWluDbMjx4PRK
Mdpz8XPFAgMBAAECggEAYosOXzy+fW55ksTgGpOGzptBfOPM8CEXvb8Tc8HfpMPk
NJ489McFsFKaXF93V5kuaEVllKQssLS3XiwzO6jA7WD8y+eIGxNO/t2+tZ1xAc3F
Ft0tHrnXjlba9RGqDF88tOvN5et7DoAJa5xMGo1TejgvKgP+3KOkLObtU3pKDryi
gSjiloxrNqv4VWYxWqP12bKQLjkE/0KPG5czDjl9Volc0OAnE18Zr7VxP/VgM/WN
9A/mv6wnWQogammIW+Wt8Uk9+G78OfthpErSJe4cD//lK/k2ChXbtsmcLHVrOsNz
x2HXo1ymuYToROSpxxPXGAGb6F3kYSVd+WAlaAJKAQKBgQDzLFNtFkfx/Hm98695
QKtBc7UxiMG4KMmQmshgltznhW30m6LC2FmQrdMVe1pta1ODUsxvxKTmsa7R9Vwt
b3qTijmQijPjQgnBctzeaMTwyfDF2cIuDdr7UDnUKgozjqulipCTlszP0aLqlbbQ
RNP8xErzioK7wUHUjmIuT69fcQKBgQDC94AKr/bIUugMqRAAWYYb2bLX3N2LTklm
mSYgj1RiMSwfmU2fhB30yeZ42qjPP11G8QFFTlfASudRi2K4+f10ZphyO2/LG22K
aDzLUlXHgRnV/OKAdoxmlq+aDg3d3qv8fUQfYe75cucM+9ILtyCQaW85Jpeeqzws
BGoFd6fXlQKBgQDazYKPgGHiChQc59x3FMpDjXJ3DJ+KLiEX3T35MyW3qKaEV1n/
Sh5lARMSnDiEhfLSEjljRCRAc5Zi0wxK0akQgmpDdSc1ECGpD8pO0SSLqJjd3Y9M
Uyk7wjcWgXFGbNRjkqd+NU06nV2jCG1DPvsj0BfExVfWyxCJykfrdcXN8QKBgASH
HvAgmgiY9E6m9normhO3gJHGzVZY4ReC4wHKklkdbzrkoorb1J5EuheAbH8zp4To
P/FOGneaxbh9FjPZimtTnqK4gqYi4u5d8Vt/dAKIGwN/NftpxWT0hut6/BN1AmWA
uz5HVfdxFbCVgJFJFXaFHFIldUv4ChOznoq19q3pAoGBAKKvskK3bWVO3uUO6jHb
J2IgmFVaYHFx6JRTHa7jsbUTmYk0xDmO8jN6HIt6O9zE05wDwunaGi5QneVtgJEA
G6y0FZAowR/8Y/qDqfwJfqDilPb7MqllOlucSJiQhIRdNixb1H1HzX6pH9hXktYk
0IHsEKcMr/P/gMCXxFfl1xAi
-----END PRIVATE KEY-----"""

rsa_public_key = """-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAuTKwnXm6ihvFg9Xaht5bwB4v+5NOUI/Tl6E4V4ufu6pSSH1W4ea0
tFvuQZ0gpYCaHaCbtKnaryPxVsTewiD7DZSZutlTtUNRlzQTK5uBI8HMPCe654+j
gMf7Y6Nvvzs08ga3P1HvKMfau9uG83FGHoHcMQDUIlDvRCYDmaHl34UY9vtfVsUc
4VFXCyXUo3PKZ14gEnh3nlxOZuVkPE7a1T+4MdzixNCmhf1WHPoEiBUsD4TYXgFX
6q9YGUeGMeWTAOf4VJ9PhlarZ9kMseLEBmqNIDgMNtnyWdMxp7/p2FZFfpBFxhTz
xi4+0fAYYpigh1pbg2zI8eD0SjHac/FzxQIDAQAB
-----END RSA PUBLIC KEY-----"""

rsa_public_key_old = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0gt2BufmgMtttnElCIcn
NIk89LGw5Oi6MBjEAIX4GejOfWB75BDgGqmfvK62rL1SieMcYYFfhe9C1UO+vZlz
Zl3sEkXcTipkYRvST0NVyM9d/fZsYCVP+wkWCOzHFol/pwVR2imKx0CEK02wyteq
NhIoziSVY4IkuShTpGHCZf6R6fugHlAaERTbTguQUoAApt4p5ASDiG6iRV8mQ54p
CTYTzbHTsZuHs147yME6dlIICXybgHxHB4YFJW/1sN09rQMzw13bKTfnuAo9p6/b
RC9xE9SY8BR+ICEDwC9a/Arm95slvPD7DJ8coBmehIj8zHXvdwjLPZoQWeLx6e/e
JwIDAQAB
-----END PUBLIC KEY-----"""

rsa_private_key_old = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDSC3YG5+aAy222
cSUIhyc0iTz0sbDk6LowGMQAhfgZ6M59YHvkEOAaqZ+8rrasvVKJ4xxhgV+F70LV
Q769mXNmXewSRdxOKmRhG9JPQ1XIz1399mxgJU/7CRYI7McWiX+nBVHaKYrHQIQr
TbDK16o2EijOJJVjgiS5KFOkYcJl/pHp+6AeUBoRFNtOC5BSgACm3inkBIOIbqJF
XyZDnikJNhPNsdOxm4ezXjvIwTp2UggJfJuAfEcHhgUlb/Ww3T2tAzPDXdspN+e4
Cj2nr9tEL3ET1JjwFH4gIQPAL1r8Cub3myW88PsMnxygGZ6EiPzMde93CMs9mhBZ
4vHp794nAgMBAAECggEAAIQYsSGmtlBJn7Ydcizq0r03kh5Roe5UbsPQz3OEzYN9
5l7zTvcfpdEe3FbNihUY+8+8BR1NP8X7swxsjoiu+ORoLQ9Q4DxIbNilpp4yusCP
qY0ObRoKXUKDdFgokQybbKydq9yIQ78L1BNnyMfI2kMnKIJ8f3cVYgMQWYoH8Toy
uzHdIOSfBWpJsRnftaHiYfaRcFPPz2KTtharKehjHuHg97JPX9bpWqCwmRIIGMJh
SA0mDwaTnn2lnIFM6S73tjpvVRj/tWhdAOGHEWVJI84JVl7XxFohsqscvzF38Iqg
RzsHX6iCxP4moW32zs9blR1Jt0MPytyqdTzuNmBVGQKBgQD4jt4Hcrzwl99+D8eP
5+i/lYFTmr3eNPY5bl45En2VbWB/TqenD4UFFmE5PjcLbwN5ep29JhphkSt25W40
Q7SVhWVTYGpdzOWk26ot0yTGhX3R3jL8n2UeF59p/ed872YrCPPP9Fu9BX80W1rJ
A2TUUdSiFZ/+InYxeI2C1kQvAwKBgQDYVWY5pzPlCwC42TE42oqCgL7IJE5go/Kw
7KkSb9qRlxCmqYetML0otlwODYOOw8QoG7PDC3WKuLad6LGXULsb6vYHSpLNzrEC
3rYBpEdyaiPhWFN6nStSCmXoxrVe1BeBU+3tVkg9OiIYozQfAaxHh459zEwX9dcJ
9voVi6YpDQKBgHjsqMBe5eT3PlgKPUCZxvZOOhj+k5jjk1blhxmlEUv9ZpEJJy9z
sXeEJ9C9n/IEFGCpcsxvGS6WfdreS/tJZTXJLD6gDZ+M67yE0gpxStb6YvgTbiLR
OVSmkXvzdwelQMN3G4b0jx0q63QBbe2VpRxWo2gntSrigTYYPGCG9a0ZAoGAI5Zg
26kay1n1A3OPOlgRIwjE2a3HSvSNbvdvlL3bycl9Dr2iuSXkaDcfi5xDgQ/JTAPK
nZJcArcCK5Xk6Qx5y0zqriZhYgPXcK5saHa63iKBxoc+LFSAlN1rCFDv8yqWt0q0
QC/KcHAIvd7TKyqeSaIOGbmq5uIlPtlnKHYxnl0CgYAb+UuMLfSP4enXvKVFZgON
bDRGKP4IORs2hrpFOuizxohnKF5cggtRMPLzwdlq4No7cZoRbM73e1K7V5IJtWZp
rZ2mIWlJRzcwx2v7/uLCJg6d5HZnKIYXQr8w21auLNSSTwLCc5juQJSwWQZ4b1Hp
Kaf8FocKH0NE2kRer1XpuA==
-----END PRIVATE KEY-----"""
